FROM node:18-alpine

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile --non-interactive

WORKDIR /app/packages/backhouse

RUN yarn build

ENV NODE_ENV production

ENTRYPOINT [ "yarn", "start" ]