version: "3"

services:
  local-db:
    container_name: local-db
    image: postgres
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
      - PGPORT=${APP_DB_PORT}
    volumes:
      - local-db:/var/lib/postgresql/data
    restart: always
    network_mode: host

volumes:
  local-db:
    driver: local