FROM node:18-alpine AS runner
WORKDIR /app

COPY . /app

RUN yarn install --frozen-lockfile --non-interactive --production=false

ENV NODE_ENV production

WORKDIR /app/packages/backhouse

CMD ["yarn", "start"]
