FROM node:18-alpine AS runner
WORKDIR /app

COPY . /app

RUN yarn install --frozen-lockfile --non-interactive --production=true

ENV NODE_ENV production

WORKDIR /app/packages/backhouse

RUN yarn build

CMD ["yarn", "start"]
