version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  sst_deploy:
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    parameters:
      stage:
        type: enum
        enum:
          - staging
          - production
    steps:
      - attach_workspace:
          at: ~/project

      - checkout

      - setup_remote_docker:
          version: 20.10.14

      - aws-cli/setup:
          role_arn: $AWS_OIDC_ROLE_ARN
          role_session_name: "Timesheeter-${CIRCLE_WORKFLOW_JOB_ID}"

      # Install the latest npm - the node Orb takes care of it
      - node/install
      # Install pnpm
      - run:
          name: Install pnpm
          command: npm i -g pnpm
      # Restore pnpm store from cache (if you want to cache the pnpm store but not the node_modules)
      - restore_cache:
          keys:
            - v1-pnpm-store-{{ checksum "pnpm-lock.yaml" }}
            - v1-pnpm-store-
      - run: pnpm install
      # Save pnpm store to cache (again, only if you want to cache the pnpm store)
      - save_cache:
          key: v1-pnpm-store-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - "~/.pnpm-store"

      # Make everything un the projects folder have 777 permissions
      - run: chmod -R 777 .

      # Run pnpm audit and fail if there are vulnerabilities high or critical
      - run:
          name: Audit
          command: pnpm audit --audit-level high

      # Run the timesheeter-env.sh script to set the AWS environment variables
      - run: chmod u+x ./.circleci/timesheeter-env.sh
      - run: ./.circleci/timesheeter-env.sh

      - run:
          name: Deploy
          # run the pnpm deploy:
          command: pnpm deploy:<< parameters.stage >>

workflows:
  build_and_deploy:
    jobs:
      # On staging branch, deploy to staging
      - sst_deploy:
          stage: staging
          filters:
            branches:
              only: staging
      # On main branch, deploy to production
      - sst_deploy:
          stage: production
          filters:
            branches:
              only: main
